# GoReleaser configuration for Yoink
version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: yoink
    binary: yoink
    main: ./cmd/yoink
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Skip windows arm64 as it's less common
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/jordangarrison/yoink/internal/version.Version={{.Version}}
      - -X github.com/jordangarrison/yoink/internal/version.Commit={{.Commit}}
      - -X github.com/jordangarrison/yoink/internal/version.Date={{.Date}}

archives:
  - id: yoink
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Enhancements'
      regexp: '^.*?enhance(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: jordangarrison
    name: yoink
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Yoink {{ .Tag }}

    Automatically revoke exposed credentials before they can be exploited.

  footer: |
    ## Installation

    ### Using Go
    ```bash
    go install github.com/jordangarrison/yoink/cmd/yoink@{{ .Tag }}
    ```

    ### Download Binary
    Download the appropriate binary for your platform from the assets below.

    **Full Changelog**: https://github.com/jordangarrison/yoink/compare/{{ .PreviousTag }}...{{ .Tag }}

# Optional: Homebrew tap (uncomment when ready)
# brews:
#   - name: yoink
#     homepage: https://github.com/jordangarrison/yoink
#     description: "Automatically revoke exposed credentials"
#     license: MIT
#     repository:
#       owner: jordangarrison
#       name: homebrew-tap

# Optional: Docker images (uncomment when ready)
# dockers:
#   - image_templates:
#       - "ghcr.io/jordangarrison/yoink:{{ .Version }}-amd64"
#       - "ghcr.io/jordangarrison/yoink:latest-amd64"
#     use: buildx
#     goarch: amd64
#     build_flag_templates:
#       - "--platform=linux/amd64"
